### ISSUE TITLE
[Card search] Add option for full text card search

### ISSUE THREAD

**Issue by MaxMihawk** [KittySparkles/stormbound-kitty#317]

**Comment by KittySparkles** [comment]
@MaxMihawk Hey Max! Do you think we could narrow down what we want from this? It’s pretty broad of a feature, so a list of expectations would help me get it sorted. :)

**Comment by MaxMihawk** [comment]
Adding a field for free text searching to search the ruletext of all cards in the game. It should ignore capitalization. The entry line looks like the one for the card names (see screenshot).

**Example 1:**
You write "on play" in the entry line and hit return.
--> You get a list of all cards with "on play" in their ruletext:

- "Bigthrust Tigers"
- "Brood Sages"
- "Copperskin Ranger"
- etc.

**Example 2:**
You write "poison" in the entry line and hit return.
--> You get a list of all cards with "poison" in their ruletext:

- "Brood Sages" (... surrounding **poison**ed unit ...)
- "Copperskin Ranger" (On play, **poison** 1...)
- etc.

![Unbenannt](https://user-images.githubusercontent.com/19865256/123522907-d1642c00-d6c0-11eb-98db-f0c839745a9f.png)

---

I know, you already have the field "ABILITY" to search for some effects, but the full text search gives a much higher flexibility. And its always up to date as long as new cards are get entered. (The search for ABILITY "Chip" gives 8 targets, so its definitly not tidy). Maybe you can remove the ornate "ABILITY" field. It seems to be to much work anyway (because its not actual).

**Comment by KittySparkles** [comment]
Thank you for taking the time to explain what you’d like. There are a few things to unpack here, so here are my replies in no particular order. Happy to hear your thoughts. :)

> Adding a field for free text searching to search the ruletext of all cards in the game. It should ignore capitalization
Alright, that’s a very fair request. You are entirely right that we currently do not have the ability to freely search for text present in the cards’ ability. I think we can definitely make that work relatively easily. Thanks for the examples, they are very straightforward.

> And its always up to date as long as new cards (or changed ones) are entered. (The search for ABILITY "Chip" gives 8 targets, so its definitly not tidy). Maybe you can remove the ornate "ABILITY" field. It seems to be to much work anyway (because its not actual).

Funny thing, the “chip” search option is the only one that is not fully automated, because it’s difficult to do so. All the others are working impeccably as far as I can tell. What do you think is missing from the chip results? I’m happy issuing a fix.

> So my suggestion is:
> - Remove the ABILITY dropdown
> - add a free text field (as the NAME field)

What about keeping the ability field as it is, and making the existing text field search through both name and ability as free text instead?

> (optional: give alternative searchoptions if you suspect a typo)
This is actually not overly difficult to do since I’m already running fuzzy searches, but the results and the expectations may vary from person to person. Some people find fuzzy searches better, some people find them confusing, sometimes showing results they don’t understand, so I think I’ll put a pin in this.

> If you don´t have the ruletexts in the database already, make a new 1:1 field, keyid of card to textfield (maybe we should think about an extension for different languages in the future so just dont close this door when giving a name fo the column) and get the textlist from SY as csv (or another easy way?).

FYI, there is no database per se, it’s just [this JSON file](https://github.com/KittySparkles/stormbound-kitty/blob/main/src/data/cards.json). And when it comes to integration with Sheepyard, well, I don’t see that happening. Generally speaking they do not have the bandwidth to invest in connecting with 3rd parties, so I don’t think we’ll ever see proper integration between the site and the game.

**Comment by MaxMihawk** [comment]
> Funny thing, the “chip” search option is the only one that is not fully automated, because it’s difficult to do so. All the others are working impeccably as far as I can tell. What do you think is missing from the chip results? I’m happy issuing a fix. (Edit: adding Temple of the Hearth, which was missing.)

I would at least add: Vindicators, Ubass, Booming Professors

> What about keeping the ability field as it is, and making the existing text field search through both name and ability as free text instead?

That´s a nice idea :) .

> > (optional: give alternative searchoptions if you suspect a typo)
> 
> This is actually not overly difficult to do since I’m already running fuzzy searches, but the results and the expectations may vary from person to person. Some people find fuzzy searches better, some people find them confusing, sometimes showing results they don’t understand, so I think I’ll put a pin in this.

To make it more transparent, the fuzzy logic should not just spit out the suspected searchtargets. I asume, that the nicest way is to _offer_ the alternative search criteria in response to a search without a result. Look at this example: https://scryfall.com/search?q=Dark+Sooul
It says:
```
0 cards found where the name includes “dark” and the name includes “sooul”
Did you mean: **dark soul**
```

> FYI, there is no database per se, it’s just [this JSON file](https://github.com/KittySparkles/stormbound-kitty/blob/main/src/data/cards.json). And when it comes to integration with Sheepyard, well, I don’t see that happening. Generally speaking they do not have the bandwidth to invest in connecting with 3rd parties, so I don’t think we’ll ever see proper integration between the site and the game.

As i can see, you already have the complete data. I was only talking about a partial dump of their database to not write all card texts by hand. WotC (owner of MtG) provides textfiles for each series, so 3rd party pages can just read in the parameters to their databases. Writing all by hand is very much work, but as mentioned above... you already have all the data :) .

So this change is pretty easy to implement I guess 👍 .

**Comment by KittySparkles** [comment]
Done with #320.
